# Generated by Django 4.0 on 2022-07-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='geo_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.EmailField(max_length=100),
        ),
    ]
