# Generated by Django 4.0 on 2022-08-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_alter_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
