# Generated by Django 4.0 on 2022-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_remove_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
